version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    # Base linters (enabled by default)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Code quality
    - dupl
    - gocyclo
    - goconst
    - prealloc
    - unconvert
    - unparam

    # Style
    - revive
    - misspell

    # Security
    - gosec

    # Testing
    - ginkgolinter
    - testpackage

    # Additional quality linters
    - nakedret
    - lll
    - gocritic
    - gocognit
    - nestif
    - err113
    - nolintlint
    - whitespace
    - wsl
