run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - goconst
    - prealloc
    - unconvert
    - revive
    - misspell
    - gosec
    - ginkgolinter
    - testpackage
    - nakedret
    - gocritic
    - nestif
    - nolintlint
    - whitespace
    - gofmt
    - goimports
    - exportloopref
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - forcetypeassert
    - nilerr
    - nilnil
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
  disable:
    - typecheck  # Disabled due to controller-runtime interface resolution issues
    - exhaustive  # Too noisy for this codebase
    - exhaustruct  # Too restrictive for Kubernetes resources
    - cyclop  # Redundant with gocyclo
    - funlen  # We have gocyclo for complexity
    - gochecknoglobals  # Kubernetes controllers often need globals
    - gomnd  # Too noisy for configuration values
    - varnamelen  # Too restrictive
    - wrapcheck  # Too noisy for controller error handling
    - wsl  # Too many style violations, needs separate cleanup
    - dupl  # Too strict for this codebase
    - gocognit  # Too strict for this codebase
    - gocyclo  # Too strict for this codebase
    - lll  # Too strict for this codebase
    - unparam  # Too strict for this codebase
    - unused  # Too strict for this codebase
    - errcheck  # Too strict for this codebase

linters-settings:
  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  dupl:
    threshold: 100

  lll:
    line-length: 120
    tab-width: 4

  misspell:
    locale: US
    ignore-words:
      - "Neo4j"
      - "neo4j"
      - "kubernetes"
      - "kubectl"

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G204  # Subprocess launched with variable
      - G304  # File path provided as taint input

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - unnamedResult
      - hugeParam
      - rangeValCopy
      - commentedOutCode
      - ifElseChain

  nestif:
    min-complexity: 5

  revive:
    rules:
      - name: exported
        disabled: true  # Too noisy for generated code
      - name: package-comments
        disabled: true  # Not required for internal packages
      - name: var-naming
        disabled: true  # Kubernetes naming conventions differ

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy for Kubernetes structs
      - shadow  # Too strict for this codebase

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: false  # Don't check exported functions in controllers

  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

  ginkgolinter:
    suppress-len-assertion: true
    suppress-nil-assertion: true
    suppress-err-assertion: true
    suppress-compare-assertion: true
    suppress-async-assertion: true
    suppress-type-compare-assertion: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst
        - unparam
        - unused
        - deadcode
        - varcheck
        - structcheck

    # Exclude some linters from generated files
    - path: zz_generated\.deepcopy\.go
      linters:
        - lll
        - gocyclo
        - dupl
        - gocritic
        - staticcheck
        - unused

    # Exclude some linters from main.go as it often has unused CLI params
    - path: cmd/main\.go
      linters:
        - unparam
        - unused

    # Allow long lines in generated files and API types
    - path: api/.*\.go
      linters:
        - lll
        - goconst

    # Exclude some linters from webhook files
    - path: internal/webhooks/.*\.go
      linters:
        - unparam
        - unused

    # Exclude some linters from controller files for embedded client methods
    - path: internal/controller/.*\.go
      text: "undefined: (Get|Create|Update|Delete|List|Status|Patch)"
      linters:
        - typecheck

    # Exclude Ginkgo/Gomega undefined errors in test files
    - path: .*_test\.go
      text: "undefined: (Describe|Context|It|By|BeforeEach|AfterEach|BeforeSuite|AfterSuite|Expect|Eventually|Consistently|Succeed|Equal|BeTrue|BeFalse|BeNil|HaveOccurred|MatchError|ContainSubstring|RegisterFailHandler|RunSpecs|GinkgoWriter|Skip|BeZero|BeNumerically|BeEmpty|HaveLen|HaveKey|HaveValue|ContainElement|MatchRegexp|MatchJSON|MatchYAML|BeEquivalentTo|BeIdenticalTo|BeAssignableToTypeOf|Panic|BeTemporally|BeAnExistingFile|BeDirty|BeRegularFile|BeADirectory|BeARegularFile|HavePrefix|HaveSuffix|HaveHTTPStatus|HaveHTTPHeaderWithValue|HaveHTTPBody|Receive|BeClosed|BeSent|HaveCap|HaveExistingField|HaveField|HaveExactFields|HaveKeyWithValue|HaveEach|Fail|GinkgoRandomSeed|Ordered|BeforeAll|AfterAll)"
      linters:
        - typecheck

    # Exclude controller-runtime client interface issues
    - text: "has no field or method (Get|Create|Update|Delete|List|Status|Patch)"
      linters:
        - typecheck

    # Exclude k8s.io import issues
    - text: "could not import k8s.io"
      linters:
        - typecheck

    # Exclude apimachinery import issues
    - text: "could not load export data.*k8s.io/apimachinery"
      linters:
        - typecheck

    # Common patterns to exclude
    - text: "G104:"  # Unchecked errors in defer statements
      linters:
        - gosec

    # Allow magic numbers in test files
    - path: .*_test\.go
      text: "Magic number"
      linters:
        - gocritic

    # Allow long parameter lists in constructors
    - text: "hugeParam.*constructor"
      linters:
        - gocritic

    # Allow empty blocks in switch statements
    - text: "empty-block"
      linters:
        - gocritic

    # Exclude some patterns from specific directories
    - path: hack/.*
      linters:
        - gosec
        - errcheck
        - gocritic

    - path: scripts/.*
      linters:
        - gosec
        - errcheck
        - gocritic
  exclude:
    # Default excludes from golangci-lint
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
    - "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"
    - "G104: Errors unhandled\\."
    - "G204: Subprocess launched with variable"
    - "G304: Potential file inclusion via variable"
