# Three-node Neo4j Enterprise cluster example (TLS disabled for testing)
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: three-node-cluster
  namespace: default
spec:
  edition: enterprise

  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  topology:
    primaries: 3
    secondaries: 0

  storage:
    className: standard
    size: "20Gi"      # Reduced for testing

  resources:
    requests:
      memory: "2Gi"   # Reduced for testing
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2"

  # TLS disabled for testing (no cert-manager required)
  tls:
    mode: disabled

  service:
    type: ClusterIP

  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"

  # Custom Neo4j configuration for production
  config:
    dbms.logs.query.enabled: "INFO"
    dbms.transaction.timeout: "60s"
    metrics.enabled: "true"
