apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jBackup
metadata:
  name: simple-backup
  labels:
    environment: development
    backup-type: one-time
spec:
  # target.kind=Cluster backs up all databases on the cluster
  target:
    kind: Cluster
    name: single-node-cluster  # References your Neo4jEnterpriseCluster name
  storage:
    type: pvc
    pvc:
      name: backup-storage
      storageClassName: standard  # Must match an available StorageClass
      size: 50Gi
  options:
    compress: true
    backupType: FULL  # FULL | DIFF | AUTO
  retention:
    maxCount: 5

---
# Pre-create the PVC (or let the operator create it via spec.storage.pvc)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
