# ============================================================
# S3 Backup — Variant 1: Explicit AWS credentials via Secret
# ============================================================
#
# Create the AWS credentials secret first:
#   kubectl create secret generic aws-backup-credentials \
#     --from-literal=AWS_ACCESS_KEY_ID=<your-access-key-id> \
#     --from-literal=AWS_SECRET_ACCESS_KEY=<your-secret-access-key>
#
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jBackup
metadata:
  name: s3-backup
  labels:
    environment: production
    backup-type: cloud
spec:
  target:
    kind: Cluster
    name: single-node-cluster  # References your Neo4jEnterpriseCluster name
  storage:
    type: s3
    bucket: my-neo4j-backups           # S3 bucket name
    path: cluster-backups              # Path/prefix within the bucket
    cloud:
      provider: aws
      credentialsSecretRef: aws-backup-credentials  # Secret with AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
  options:
    compress: true
    backupType: FULL
    # tempPath is recommended for cloud uploads to avoid partial writes
    tempPath: /tmp/neo4j-backup-temp
  retention:
    maxAge: "30d"
    maxCount: 30

---
# AWS credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: aws-backup-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <your-access-key-id>
  AWS_SECRET_ACCESS_KEY: <your-secret-access-key>

---
# ============================================================
# S3 Backup — Variant 2: Workload Identity (IRSA / EKS Pod Identity)
#
# Use this when your EKS nodes/pods have an IAM role that grants
# S3 access — no static credentials needed.
# ============================================================
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jBackup
metadata:
  name: s3-backup-irsa
  labels:
    environment: production
    backup-type: cloud
spec:
  target:
    kind: Cluster
    name: single-node-cluster
  storage:
    type: s3
    bucket: my-neo4j-backups
    path: cluster-backups
    cloud:
      provider: aws
      identity:
        autoCreate:
          annotations:
            # Annotate the ServiceAccount with your IAM role ARN for IRSA
            eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/neo4j-backup-role
  options:
    compress: true
    backupType: FULL
    tempPath: /tmp/neo4j-backup-temp
  retention:
    maxAge: "30d"
    maxCount: 30
