apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jBackup
metadata:
  name: simple-backup
  labels:
    environment: development
    backup-type: one-time
spec:
  target:
    kind: Cluster
    name: single-node-cluster  # Reference to your Neo4j cluster
  storage:
    type: pvc
    pvc:
      name: backup-storage
      size: 50Gi
      storageClass: standard
  options:
    compress: true
    verify: true
  retention:
    maxCount: 5

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
