/*
Copyright Neo4j.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package oracle

import (
	"fmt"
	"strings"
)

// Generated blocks in the two pages below. The prose around them is written by hand, so only what
// sits between a pair of markers is replaced.
const (
	BlockCatalog    = "oracle:catalog"
	BlockSteady     = "oracle:steady"
	BlockConditions = "oracle:conditions"
)

// The three projections, relative to the module root.
const (
	DocPath       = "docs/user-guide/05-reference/errors.md"
	StatusDocPath = "docs/design/crd-spec/neo4j/status.md"
	ShellPath     = "tests/lib/oracle.sh"
)

// eventConditionCell is how an Event-only row names its (absent) condition.
const eventConditionCell = "— (Event only)"

// EventKey is the condition name the shell oracle uses for Event-only reasons, since a lookup
// keyed on the empty string would be indistinguishable from a caller passing nothing.
const EventKey = "event"

// RenderMarkdown returns the error reference with both reason tables refreshed from the catalog.
func RenderMarkdown(page string) (string, error) {
	out, err := replaceBlock(page, DocPath, BlockCatalog, table(problemRows()))
	if err != nil {
		return "", err
	}
	return replaceBlock(out, DocPath, BlockSteady, table(steadyRows()))
}

// RenderStatusMarkdown returns the status contract with the condition table refreshed. The
// conditions the operator writes are declared once, in the catalog, so the contract page cannot
// keep advertising a condition that was renamed or never implemented (ADR-014).
func RenderStatusMarkdown(page string) (string, error) {
	return replaceBlock(page, StatusDocPath, BlockConditions, conditionTable())
}

func conditionTable() string {
	var b strings.Builder
	b.WriteString("| Type | `True` when | Blocks `Ready`? |\n")
	b.WriteString("|------|-------------|-----------------|\n")
	for _, c := range conditions {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", c, c.Summary(), c.Gate())
	}
	return b.String()
}

func problemRows() []Entry {
	var out []Entry
	for _, e := range entries {
		if !e.Nominal {
			out = append(out, e)
		}
	}
	return out
}

func steadyRows() []Entry {
	var out []Entry
	for _, e := range entries {
		if e.Nominal {
			out = append(out, e)
		}
	}
	return out
}

func table(rows []Entry) string {
	var b strings.Builder
	b.WriteString("| Condition | Reason | Severity | Surface | Meaning |\n")
	b.WriteString("|-----------|--------|----------|---------|---------|\n")
	for _, e := range rows {
		condition := e.Condition.String()
		if e.Condition.IsZero() {
			condition = eventConditionCell
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n",
			condition, e.Reason, e.Severity, e.Surface, e.Summary)
	}
	return b.String()
}

func replaceBlock(page, rel, name, body string) (string, error) {
	begin := fmt.Sprintf("<!-- BEGIN GENERATED %s -->", name)
	end := fmt.Sprintf("<!-- END GENERATED %s -->", name)
	i := strings.Index(page, begin)
	j := strings.Index(page, end)
	if i < 0 || j < 0 {
		return "", fmt.Errorf("%s: markers %s / %s not found — the page must keep them around the generated table", rel, begin, end)
	}
	if j < i {
		return "", fmt.Errorf("%s: marker %s appears before %s", rel, end, begin)
	}
	newline := "\n"
	// Pages in docs/design/ are committed with CRLF; emitting LF into one would leave the
	// projection permanently stale and every regeneration would rewrite the whole block.
	if strings.Contains(page, "\r\n") {
		newline = "\r\n"
		body = strings.ReplaceAll(body, "\n", "\r\n")
	}
	return page[:i+len(begin)] + newline + body + page[j:], nil
}

// RenderShell returns tests/lib/oracle.sh: the same catalog as shell lookups, so an e2e assert
// asks the operator's contract for a reason instead of hardcoding the string (ADR-014).
func RenderShell() string {
	var b strings.Builder
	b.WriteString(`#!/usr/bin/env bash
# Generated by ` + "`make errors`" + ` from src/internal/oracle/catalog.go — do not edit.
#
# The condition reasons the operator can emit, as the operator declares them. Asserts source this
# file so a rename in Go breaks one generated line instead of leaving a stale string in a dozen
# scripts. Functions rather than associative arrays: bash 3.2 on macOS has none.
#
#   oracle_reasons_for <condition>   every reason that condition can carry (` + EventKey + ` for Event-only)
#   oracle_has <condition> <reason>  whether the pairing is catalogued
#   oracle_known_reason <reason>     whether the reason exists at all, under any condition
#   oracle_severity <reason>         error | warn | info
#   oracle_nominal <reason>          success if the reason means things are fine

oracle_conditions() {
`)
	b.WriteString("  printf '%s\\n'")
	for _, c := range conditions {
		fmt.Fprintf(&b, " %s", c)
	}
	b.WriteString("\n}\n\noracle_reasons_for() {  # <condition>\n  case \"$1\" in\n")
	for _, c := range conditions {
		reasons := ReasonsFor(c)
		if len(reasons) == 0 {
			continue
		}
		fmt.Fprintf(&b, "    %s) printf '%%s\\n'", c)
		for _, r := range reasons {
			fmt.Fprintf(&b, " %s", r)
		}
		b.WriteString(" ;;\n")
	}
	if events := ReasonsFor(Condition{}); len(events) > 0 {
		fmt.Fprintf(&b, "    %s) printf '%%s\\n'", EventKey)
		for _, r := range events {
			fmt.Fprintf(&b, " %s", r)
		}
		b.WriteString(" ;;\n")
	}
	b.WriteString(`    *) return 1 ;;
  esac
}

oracle_has() {  # <condition> <reason>
  oracle_reasons_for "$1" 2>/dev/null | grep -qxF "$2"
}

oracle_known_reason() {  # <reason>
  oracle_severity "$1" >/dev/null
}

oracle_severity() {  # <reason>
  case "$1" in
`)
	for _, r := range distinctReasons() {
		e, _ := lookupByReason(r)
		fmt.Fprintf(&b, "    %s) echo %s ;;\n", r, e.Severity)
	}
	b.WriteString(`    *) return 1 ;;
  esac
}

oracle_nominal() {  # <reason>
  case "$1" in
`)
	nominal := nominalReasons()
	if len(nominal) > 0 {
		b.WriteString("    ")
		for i, r := range nominal {
			if i > 0 {
				b.WriteString("|")
			}
			b.WriteString(r.String())
		}
		b.WriteString(") return 0 ;;\n")
	}
	b.WriteString(`    *) return 1 ;;
  esac
}
`)
	return b.String()
}

// distinctReasons lists every reason once, in declaration order — a reason may be catalogued
// under two conditions (UnsupportedSinglePrimary).
func distinctReasons() []Reason {
	seen := map[Reason]bool{}
	var out []Reason
	for _, e := range entries {
		if !seen[e.Reason] {
			seen[e.Reason] = true
			out = append(out, e.Reason)
		}
	}
	return out
}

func nominalReasons() []Reason {
	var out []Reason
	for _, r := range distinctReasons() {
		if e, ok := lookupByReason(r); ok && e.Nominal {
			out = append(out, r)
		}
	}
	return out
}

func lookupByReason(r Reason) (Entry, bool) {
	for _, e := range entries {
		if e.Reason == r {
			return e, true
		}
	}
	return Entry{}, false
}
