apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jBackup
metadata:
  name: full-backup
  namespace: default
spec:
  # target.name references the Neo4jEnterpriseCluster name directly —
  # there is no top-level spec.clusterRef field.
  target:
    kind: Cluster          # Backs up all databases on the cluster
    name: my-neo4j-cluster
  # schedule is a flat cron string — not spec.schedule.cron
  schedule: "0 2 * * *"  # Daily at 2 AM UTC
  options:
    backupType: FULL       # FULL | DIFF | AUTO
    compress: true
    pageCache: "4G"        # Memory allocated to page-cache during backup
  storage:
    type: pvc
    pvc:
      name: backup-pvc
      storageClassName: fast-ssd
      size: 100Gi
  retention:
    maxAge: "7d"
    maxCount: 7
