# Neo4j cluster example for read-heavy workloads
# This creates a cluster with 5 servers
# Databases can be configured with read replicas for horizontal scaling

apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: cluster-with-replicas
  namespace: default
spec:
  edition: enterprise

  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  # 5-server cluster for read scaling workloads
  # Databases can use different topologies (e.g., 3 primaries + 2 secondaries)
  topology:
    servers: 5        # More servers allow flexible database topologies

  storage:
    className: standard
    size: "30Gi"

  # Differentiated resources (optional)
  resources:
    requests:
      memory: "3Gi"
      cpu: "750m"
    limits:
      memory: "6Gi"
      cpu: "3"

  # TLS disabled for simplicity
  tls:
    mode: disabled

  # Environment variables
  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"

  # Configuration optimized for read workloads
  config:
    # Optimize for read performance
    server.memory.pagecache.size: "1g"
    # Query routing configuration for read scaling
    dbms.routing.default_router: "SERVER"
    # Enable query logging for monitoring read performance
    dbms.logs.query.enabled: "INFO"

---
# Note: Create admin secret before deploying:
# kubectl create secret generic neo4j-admin-secret \
#   --from-literal=username=neo4j \
#   --from-literal=password=your-secure-password
