# Neo4j cluster with read replicas example
# This creates a cluster with 3 primaries and 2 read replicas
# Ideal for read-heavy workloads requiring horizontal read scaling

apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: cluster-with-replicas
  namespace: default
spec:
  edition: enterprise

  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  # Cluster with read replicas for read scaling
  topology:
    primaries: 3      # Core cluster for writes and consistency
    secondaries: 2    # Read replicas for scaling read operations

  storage:
    className: standard
    size: "30Gi"

  # Differentiated resources (optional)
  resources:
    requests:
      memory: "3Gi"
      cpu: "750m"
    limits:
      memory: "6Gi"
      cpu: "3"

  # TLS disabled for simplicity
  tls:
    mode: disabled

  # Environment variables
  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"

  # Configuration optimized for read workloads
  config:
    # Optimize for read performance
    dbms.memory.pagecache.size: "1g"
    # Query routing configuration for read scaling
    dbms.routing.default_router: "SERVER"
    # Enable query logging for monitoring read performance
    dbms.logs.query.enabled: "INFO"

---
# Note: Create admin secret before deploying:
# kubectl create secret generic neo4j-admin-secret \
#   --from-literal=username=neo4j \
#   --from-literal=password=your-secure-password
