# LoadBalancer Service Example for Neo4j Enterprise Cluster
# This example shows how to expose a Neo4j cluster using a LoadBalancer service
# Uses server-based architecture with 5 servers that self-organize
# Suitable for cloud environments (AWS, GCP, Azure)

apiVersion: v1
kind: Secret
metadata:
  name: neo4j-admin-secret
type: Opaque
stringData:
  username: neo4j
  password: changeme123!  # CHANGE THIS IN PRODUCTION

---
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: loadbalancer-cluster
spec:

  image:
    repository: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  topology:
    servers: 5        # Five servers for flexible database topologies

  storage:
    className: standard  # Use appropriate storage class for your cloud
    size: "20Gi"

  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

  # LoadBalancer service configuration
  service:
    type: LoadBalancer

    # Cloud-specific annotations
    annotations:
      # AWS Network Load Balancer
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

      # GCP Load Balancer (uncomment for GCP)
      # cloud.google.com/load-balancer-type: "Internal"

      # Azure Load Balancer (uncomment for Azure)
      # service.beta.kubernetes.io/azure-load-balancer-internal: "false"

    # Restrict access to specific IP ranges
    loadBalancerSourceRanges:
      - "10.0.0.0/8"      # Corporate network
      - "172.16.0.0/12"   # VPN range
      - "192.168.0.0/16"  # Private network

    # Preserve client source IPs
    externalTrafficPolicy: Local

  # Authentication
  auth:
    provider: native
    adminSecret: neo4j-admin-secret

  # Environment variables
  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"

  # Configuration
  config:
    # Memory settings
    server.memory.heap.initial_size: "1G"
    server.memory.heap.max_size: "2G"
    server.memory.pagecache.size: "1G"

    # Query logging
    db.logs.query.enabled: "INFO"
    db.logs.query.threshold: "1s"

    # Network settings for better performance
    server.bolt.listen_address: "0.0.0.0:7687"
    server.http.listen_address: "0.0.0.0:7474"
