# Six Server Neo4j Enterprise Cluster Example
#
# This configuration uses 6 servers that self-organize into roles.
# The servers provide high availability with optimal resource utilization.
# Databases can be created with different topologies as needed.
#
# CLUSTER FORMATION: The operator uses server-based cluster formation.
# Servers self-organize and databases can use different primary/secondary topologies.
# This provides flexible database deployment options on the same cluster infrastructure.
#
# See: docs/user_guide/guides/server_based_architecture.md
#
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: six-server-cluster
  namespace: default
  annotations:
    neo4j.neo4j.com/topology-note: "6 servers provide flexible infrastructure for multiple database topologies"
spec:
  # Neo4j 5.26+ Enterprise image required
  image:
    repo: "neo4j"
    tag: "5.26.0-enterprise"
    pullPolicy: "IfNotPresent"

  # Server-based cluster configuration
  # Six servers will self-organize to host databases with configurable topologies
  topology:
    servers: 6        # Six servers for flexible database topologies
    placement:
      topologySpread:
        enabled: true
        topologyKey: "topology.kubernetes.io/zone"
        maxSkew: 1
      antiAffinity:
        enabled: true
        topologyKey: "kubernetes.io/hostname"

  # Storage configuration
  storage:
    className: "fast-ssd"
    size: "50Gi"

  # Authentication
  auth:
    adminSecret: "neo4j-admin-secret"

  # TLS configuration
  tls:
    mode: "cert-manager"
    issuerRef:
      name: "ca-cluster-issuer"
      kind: "ClusterIssuer"

  # Resource configuration for primary nodes
  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"

  # Service configuration
  service:
    type: "LoadBalancer"
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

---
# Required admin secret - create separately with:
# kubectl create secret generic neo4j-admin-secret \
#   --from-literal=username=neo4j \
#   --from-literal=password=your-secure-password
