# Three-server Neo4j Enterprise cluster example
# This creates a highly available Neo4j cluster with 3 servers
# Servers self-organize to host databases with configurable topologies

apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: three-node-cluster
  namespace: default
spec:
  # Neo4j Enterprise Edition
  edition: enterprise

  # Neo4j Docker image configuration
  image:
    repo: neo4j
    tag: "5.26-enterprise"  # Neo4j 5.26+ required
    pullPolicy: IfNotPresent

  # Three-server cluster topology for high availability
  # Servers self-organize to host databases with different topologies
  topology:
    servers: 3        # 3 servers for optimal fault tolerance

  # Storage configuration
  storage:
    className: standard
    size: "50Gi"      # Larger storage for production

  # Production resource allocation
  resources:
    requests:
      memory: "4Gi"   # Higher memory for cluster workload
      cpu: "1"        # More CPU for cluster coordination
    limits:
      memory: "8Gi"
      cpu: "4"

  # TLS with cert-manager (recommended for production)
  tls:
    mode: cert-manager
    issuerRef:
      name: ca-cluster-issuer  # Uses self-signed CA for development
      kind: ClusterIssuer      # For production, replace with your own issuer

  # Service configuration
  service:
    type: ClusterIP     # Use LoadBalancer for external access

  # Required environment variables
  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"

  # Custom Neo4j configuration for production
  config:
    # Enable query logging for monitoring
    dbms.logs.query.enabled: "INFO"
    # Increase transaction timeout for long operations
    dbms.transaction.timeout: "60s"
    # Enable metrics collection
    metrics.enabled: "true"

---
# Deployment Notes:
#
# 1. Create admin credentials first:
#    kubectl create secret generic neo4j-admin-secret \
#      --from-literal=username=neo4j \
#      --from-literal=password=your-secure-password
#
# 2. For TLS mode, cert-manager and ClusterIssuer are automatically set up:
#    Development clusters include a self-signed ClusterIssuer (ca-cluster-issuer)
#
# 3. Expected deployment time: 2-3 minutes total
#    - All server pods start in parallel (ParallelPodManagement)
#    - Servers discover each other and form cluster
#    - Databases can then be created with specific topologies
#
# 4. Monitor deployment progress:
#    kubectl get pods -l app.kubernetes.io/name=neo4j -w
