# Two Primary Node Cluster Example
#
# WARNING: This configuration uses 2 primary nodes, which provides limited fault tolerance.
# If one node fails, the remaining node cannot form quorum and the cluster becomes read-only.
# This configuration is NOT recommended for production use.
#
# CLUSTER FORMATION: The operator uses coordinated cluster formation that requires both
# nodes to start together. The cluster will wait for both primaries before accepting connections.
# This prevents split-brain scenarios but means longer startup times.
#
# For production deployments, consider using 3 primary nodes instead.
# See: docs/user_guide/guides/fault_tolerance.md
#
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: two-primary-cluster
  namespace: default
  annotations:
    neo4j.neo4j.com/fault-tolerance-warning: "true"
    neo4j.neo4j.com/topology-note: "2 primary nodes provide limited fault tolerance"
spec:
  # Neo4j 5.26+ Enterprise image required
  image:
    repo: "neo4j"
    tag: "5.26.0-enterprise"
    pullPolicy: "IfNotPresent"

  # WARNING: 2 primary nodes configuration
  # This will generate warnings from the operator:
  # - "Even number of primary nodes (2) reduces fault tolerance"
  # - "2 primary nodes provide limited fault tolerance"
  topology:
    primaries: 2      # ⚠️ Even number - not recommended
    secondaries: 1    # Add read replica for read scaling

  # Storage configuration
  storage:
    className: "standard"
    size: "20Gi"

  # Authentication
  auth:
    adminSecret: "neo4j-admin-secret"

  # TLS configuration
  tls:
    mode: "cert-manager"
    issuerRef:
      name: "ca-cluster-issuer"
      kind: "ClusterIssuer"

  # Resource configuration
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  # Service configuration
  service:
    type: "ClusterIP"
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

---
# Required admin secret - create separately with:
# kubectl create secret generic neo4j-admin-secret \
#   --from-literal=username=neo4j \
#   --from-literal=password=your-secure-password
