# Purpose: Placeholder license Secrets referenced by spec.pluginDefinitions.{gds,bloom}.licenseSecretRef.
# Prerequisites: none — but read the note below before relying on these for anything real.
# Apply: kubectl apply -f examples/secrets/plugin-licenses.yaml
# Related README: ../README.md#tls--auth--plugin-prerequisites
#
# Used by: examples/cluster/03-pools-analytics-read.yaml, examples/cluster/14-full.yaml
#
# NOTE: "REPLACE_ME" is a DUMMY placeholder, not a real license. GDS and Bloom will run in
# Community mode (or refuse Enterprise features) until you replace the "license" key with the
# actual contents of your GDS Enterprise / Bloom license file from Neo4j.
apiVersion: v1
kind: Secret
metadata:
  name: gds-license
type: Opaque
stringData:
  license: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: bloom-license
type: Opaque
stringData:
  license: REPLACE_ME
