#!/usr/bin/env bash
# Shared helpers for the e2e harness (ADR-012 estate 2).

set -euo pipefail

TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "${TESTS_DIR}/.." && pwd)"

# The operator's own reason catalog, generated by `make errors`. Every assert gets the lookups,
# so an expected reason is checked against the contract instead of being trusted as a string.
# shellcheck source=oracle.sh
source "${TESTS_DIR}/lib/oracle.sh"

log() {
  printf '[%s] %s\n' "$(date -u +%H:%M:%S)" "$*"
}

die() {
  log "ERROR: $*"
  exit 1
}

require_cmd() {
  local cmd
  for cmd in "$@"; do
    command -v "${cmd}" >/dev/null 2>&1 || die "required command not found: ${cmd}"
  done
}

# Guard for a managed cluster that already exists. The nightly creates one and tears it down
# again, but a local run — or a teardown that never completed — finds one still standing, and
# reusing it on another version would report a green run against a version nobody asked for.
# Upgrading in place is not the alternative: it takes tens of minutes and would leave the suites
# testing a control plane mid-upgrade.
#
# A requested minor matches any patch of it, because AKS and GKE are handed `1.36`, pick a patch
# themselves and report the full number back — including GKE's `-gke.NNNNNNN` build suffix.
require_cluster_version() { # <what> <running> <requested> <how to clear it>
  local what=$1 running=$2 requested=$3 remedy=$4
  case "${running}" in
    "${requested}" | "${requested}".*) return 0 ;;
  esac
  die "${what} runs Kubernetes ${running} but ${requested} was requested — ${remedy}"
}

# oracle_require fails the assert immediately when the reason it is about to wait for is not one
# the operator can emit on that condition — a rename or a typo, which otherwise costs a full
# timeout and reads like a broken operator. Pass `event` as the condition for Event-only reasons.
oracle_require() {  # <condition> <reason>
  local condition=$1 reason=$2
  oracle_has "${condition}" "${reason}" && return 0
  log "Reasons catalogued for ${condition}: $(oracle_reasons_for "${condition}" 2>/dev/null | tr '\n' ' ')"
  die "reason ${reason} is not catalogued for ${condition} — see src/internal/oracle/catalog.go, then run 'make errors'"
}

kubectl_wait_deployment() {
  local namespace=$1
  local name=$2
  local timeout=${3:-180s}
  kubectl rollout status "deployment/${name}" -n "${namespace}" --timeout="${timeout}"
}

kubectl_jsonpath() {
  kubectl get "$1" -n "${NEO4J_NAMESPACE}" -o "jsonpath={$2}"
}

resolve_action_template() {
  local template=$1
  local resolved="${template//\{\{assert\}\}/${SUITE_CASE_ASSERT:-}}"
  resolved="${resolved//\{\{id\}\}/${SUITE_CASE_ID:-}}"
  printf '%s' "${resolved}"
}

run_action() {
  local action=$1
  local mode=${2:-full}
  local action_dir="${TESTS_DIR}/actions/${action}"
  [[ -d "${action_dir}" ]] || die "unknown action: ${action}"

  case "${mode}" in
    full)
      log "ACTION run: ${action}"
      bash "${action_dir}/run.sh"
      log "ACTION verify: ${action}"
      bash "${action_dir}/verify.sh"
      ;;
    run)
      log "ACTION run: ${action}"
      bash "${action_dir}/run.sh"
      ;;
    verify)
      log "ACTION verify: ${action}"
      bash "${action_dir}/verify.sh"
      ;;
    *)
      die "unknown run_action mode: ${mode}"
      ;;
  esac
}

run_phase() {
  local label=$1
  local mode=$2
  shift 2
  local step resolved

  [[ "$#" -gt 0 ]] || return 0

  # NOTE: run_phase is called as `if ! run_phase ...`, which disables `set -e`
  # inside this function. We must therefore check each action's exit code
  # explicitly — otherwise a failing action (e.g. an assert that calls die)
  # in any position but the last would be swallowed and the phase would report
  # the last action's status. Stop on the first failure (fail-fast per phase).
  log "PHASE ${label}"
  for step in "$@"; do
    [[ -n "${step}" ]] || continue
    resolved="$(resolve_action_template "${step}")"
    if ! run_action "${resolved}" "${mode}"; then
      return 1
    fi
  done
  return 0
}

run_cleanup_phase() {
  local label=$1
  shift
  local step resolved

  [[ "$#" -gt 0 ]] || return 0

  log "PHASE ${label}"
  for step in "$@"; do
    [[ -n "${step}" ]] || continue
    resolved="$(resolve_action_template "${step}")"
    bash "${TESTS_DIR}/actions/${resolved}/run.sh" || true
  done
}

# Apply-result handoff: actions run in separate `bash` processes, so exported
# vars don't survive between deploy (case_run) and admission asserts (case_assert).
# Persist the last kubectl apply outcome to files keyed by run + case instead.
_apply_state_dir() {
  printf '%s' "${TESTS_DIR}/results/runs/${RUN_ID:-manual}/.apply-state"
}

# record_apply_result <exit_code> <stderr_file> — called by deploy after apply.
record_apply_result() {
  local exit_code=$1
  local stderr_file=$2
  local dir
  dir="$(_apply_state_dir)"
  mkdir -p "${dir}"
  printf '%s' "${exit_code}" >"${dir}/${SUITE_CASE_ID:-case}.exit"
  cp "${stderr_file}" "${dir}/${SUITE_CASE_ID:-case}.stderr" 2>/dev/null \
    || : >"${dir}/${SUITE_CASE_ID:-case}.stderr"
}

read_apply_exit() {
  cat "$(_apply_state_dir)/${SUITE_CASE_ID:-case}.exit" 2>/dev/null || printf ''
}

read_apply_stderr() {
  cat "$(_apply_state_dir)/${SUITE_CASE_ID:-case}.stderr" 2>/dev/null || printf ''
}

# read_mount_name / read_mount_path — resolved additionalMounts values persisted by
# deploy/neo4j, consumed by assert/storage-additional in a separate subprocess.
read_mount_name() {
  cat "$(_apply_state_dir)/${SUITE_CASE_ID:-case}.mount-name" 2>/dev/null || printf ''
}

read_mount_path() {
  cat "$(_apply_state_dir)/${SUITE_CASE_ID:-case}.mount-path" 2>/dev/null || printf ''
}

collect_diagnostics() {
  local run_id=${1:-manual}
  local out="${TESTS_DIR}/results/runs/${run_id}"
  mkdir -p "${out}"

  log "Collecting diagnostics into ${out}"
  kubectl get crd "${OPERATOR_CRD}" -o yaml >"${out}/crd.yaml" 2>&1 || true
  kubectl get all -n "${OPERATOR_NAMESPACE}" -o wide >"${out}/operator-all.txt" 2>&1 || true
  kubectl describe deployment -n "${OPERATOR_NAMESPACE}" >"${out}/operator-deployment.txt" 2>&1 || true
  # Whole log, not a tail: asserts read it with --tail=-1, and at a dozen reconcile passes per
  # minute a couple of hundred lines cover half a minute — never the failure they were collected for.
  kubectl logs -n "${OPERATOR_NAMESPACE}" -l "${OPERATOR_LABEL_SELECTOR}" --tail=-1 >"${out}/operator-logs.txt" 2>&1 || true
  kubectl get neo4j,sts,svc,secret,configmap,pvc,pods -n "${NEO4J_NAMESPACE}" -o wide >"${out}/workload.txt" 2>&1 || true
  kubectl describe neo4j "${NEO4J_CR_NAME}" -n "${NEO4J_NAMESPACE}" >"${out}/neo4j-describe.txt" 2>&1 || true

  # Pod-level evidence: the CR describe and operator logs don't show WHY a workload pod
  # crashes (OOMKilled, failed probe, Neo4j fatal boot error). Capture pod describe
  # (Events + Last State), current + previous container logs, and namespace events.
  # collect_diagnostics runs before case_teardown (run-suite.sh), so the pod is still alive.
  kubectl get events -n "${NEO4J_NAMESPACE}" --sort-by=.lastTimestamp \
    >"${out}/events.txt" 2>&1 || true
  if [[ -n "${NEO4J_CR_NAME:-}" ]]; then
    local selector="app.kubernetes.io/instance=${NEO4J_CR_NAME}"
    kubectl describe pod -n "${NEO4J_NAMESPACE}" -l "${selector}" \
      >"${out}/workload-pods-describe.txt" 2>&1 || true
    local pod base
    for pod in $(kubectl get pods -n "${NEO4J_NAMESPACE}" -l "${selector}" -o name 2>/dev/null); do
      base="${pod#pod/}"
      kubectl logs "${pod}" -n "${NEO4J_NAMESPACE}" -c neo4j --tail=-1 \
        >"${out}/${base}.log" 2>&1 || true
      # --previous captures the crashed container before the CrashLoopBackOff restart.
      kubectl logs "${pod}" -n "${NEO4J_NAMESPACE}" -c neo4j --previous --tail=-1 \
        >"${out}/${base}.previous.log" 2>&1 || true
    done
  fi
}
