#!/usr/bin/env bash
# Generated by `make errors` from src/internal/oracle/catalog.go — do not edit.
#
# The condition reasons the operator can emit, as the operator declares them. Asserts source this
# file so a rename in Go breaks one generated line instead of leaving a stale string in a dozen
# scripts. Functions rather than associative arrays: bash 3.2 on macOS has none.
#
#   oracle_reasons_for <condition>   every reason that condition can carry (event for Event-only)
#   oracle_has <condition> <reason>  whether the pairing is catalogued
#   oracle_known_reason <reason>     whether the reason exists at all, under any condition
#   oracle_severity <reason>         error | warn | info
#   oracle_nominal <reason>          success if the reason means things are fine

oracle_conditions() {
  printf '%s\n' Ready Reconciling Installed Error StorageReady TLSReady ClusterFormed ServersPendingDrain
}

oracle_reasons_for() {  # <condition>
  case "$1" in
    Ready) printf '%s\n' AllMembersReady MembersNotReady TLSNotReady OfflineMaintenance ReconcileError ;;
    Reconciling) printf '%s\n' InProgress Completed Failed ;;
    Installed) printf '%s\n' ObjectsCreated Pending ;;
    Error) printf '%s\n' NoError ReconcileFailed SecretNotMountable SecretNotDelegated AuthSecretInvalid ;;
    StorageReady) printf '%s\n' PVCBound PVCPending ;;
    TLSReady) printf '%s\n' TrustDisabled SecretsPresent SecretMissing CertificatePending ;;
    ClusterFormed) printf '%s\n' Formed EnablingServer BoltUnavailable BootstrapGateTooHigh ShowServersFailed UnsupportedSystemScaleUp WaitingSystemLeader WaitingQuorum UnsupportedSinglePrimary ;;
    ServersPendingDrain) printf '%s\n' UnsupportedSinglePrimary NoDrain ShrinkingTopology Draining AwaitingSTSShrink ;;
    event) printf '%s\n' DuplicateEntry DatabaseTopologyResized InsecureAdminConnection AdminBoltTLSRequired SecretMounted ;;
    *) return 1 ;;
  esac
}

oracle_has() {  # <condition> <reason>
  oracle_reasons_for "$1" 2>/dev/null | grep -qxF "$2"
}

oracle_known_reason() {  # <reason>
  oracle_severity "$1" >/dev/null
}

oracle_severity() {  # <reason>
  case "$1" in
    AllMembersReady) echo info ;;
    MembersNotReady) echo warn ;;
    TLSNotReady) echo warn ;;
    OfflineMaintenance) echo info ;;
    ReconcileError) echo error ;;
    InProgress) echo info ;;
    Completed) echo info ;;
    Failed) echo error ;;
    ObjectsCreated) echo info ;;
    Pending) echo info ;;
    NoError) echo info ;;
    ReconcileFailed) echo error ;;
    SecretNotMountable) echo error ;;
    SecretNotDelegated) echo error ;;
    AuthSecretInvalid) echo error ;;
    PVCBound) echo info ;;
    PVCPending) echo warn ;;
    TrustDisabled) echo info ;;
    SecretsPresent) echo info ;;
    SecretMissing) echo error ;;
    CertificatePending) echo warn ;;
    Formed) echo info ;;
    EnablingServer) echo info ;;
    BoltUnavailable) echo warn ;;
    BootstrapGateTooHigh) echo error ;;
    ShowServersFailed) echo error ;;
    UnsupportedSystemScaleUp) echo error ;;
    WaitingSystemLeader) echo warn ;;
    WaitingQuorum) echo warn ;;
    UnsupportedSinglePrimary) echo error ;;
    NoDrain) echo info ;;
    ShrinkingTopology) echo info ;;
    Draining) echo info ;;
    AwaitingSTSShrink) echo info ;;
    DuplicateEntry) echo warn ;;
    DatabaseTopologyResized) echo warn ;;
    InsecureAdminConnection) echo warn ;;
    AdminBoltTLSRequired) echo warn ;;
    SecretMounted) echo info ;;
    *) return 1 ;;
  esac
}

oracle_nominal() {  # <reason>
  case "$1" in
    AllMembersReady|InProgress|Completed|ObjectsCreated|NoError|PVCBound|TrustDisabled|SecretsPresent|Formed|NoDrain|SecretMounted) return 0 ;;
    *) return 1 ;;
  esac
}
