name: 'Setup Go Environment'
description: 'Sets up Go with caching and downloads dependencies'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.22'

runs:
  using: 'composite'
  steps:
    - name: Clear any existing Go cache to prevent conflicts
      shell: bash
      run: |
        rm -rf ~/.cache/go-build || true
        rm -rf ~/go/pkg/mod || true

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Download dependencies
      shell: bash
      run: go mod download
