name: 'Setup Go Environment'
description: 'Sets up Go with caching and downloads dependencies'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.22'

runs:
  using: 'composite'
  steps:
    - name: Set up Go with built-in caching
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
        cache-dependency-path: |
          go.sum
          go.mod

    - name: Download dependencies
      shell: bash
      run: go mod download
