# LoadBalancer Service Example for Neo4j Enterprise Standalone
# This example shows how to expose a standalone Neo4j instance using LoadBalancer
# Suitable for cloud environments (AWS, GCP, Azure)

apiVersion: v1
kind: Secret
metadata:
  name: neo4j-admin-secret
type: Opaque
stringData:
  username: neo4j
  password: changeme123!  # CHANGE THIS IN PRODUCTION

---
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseStandalone
metadata:
  name: loadbalancer-standalone
spec:

  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  storage:
    className: standard  # Use appropriate storage class for your cloud
    size: "20Gi"

  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

  # LoadBalancer service configuration
  service:
    type: LoadBalancer

    # Cloud-specific annotations
    annotations:
      # AWS Network Load Balancer
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"

      # GCP Load Balancer (uncomment for GCP)
      # cloud.google.com/load-balancer-type: "External"

      # Azure Load Balancer (uncomment for Azure)
      # service.beta.kubernetes.io/azure-load-balancer-internal: "false"

    # Optional: Request a specific IP (cloud provider must support this)
    # loadBalancerIP: "1.2.3.4"

    # Restrict access to specific IP ranges
    loadBalancerSourceRanges:
      - "10.0.0.0/8"      # Corporate network
      - "172.16.0.0/12"   # VPN range

    # Preserve client source IPs
    externalTrafficPolicy: Local

  # Authentication
  auth:
    provider: native
    adminSecret: neo4j-admin-secret

  # Environment variables
  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"

  # Configuration
  config:
    # Memory settings
    server.memory.heap.initial_size: "1G"
    server.memory.heap.max_size: "2G"
    server.memory.pagecache.size: "1G"

    # Enable APOC procedures
    dbms.security.procedures.unrestricted: "apoc.*"

    # Query logging
    db.logs.query.enabled: "INFO"
    db.logs.query.threshold: "1s"

    # Network settings
    server.bolt.listen_address: "0.0.0.0:7687"
    server.http.listen_address: "0.0.0.0:7474"

---
# Optional: Install APOC plugin using Neo4jPlugin CRD
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jPlugin
metadata:
  name: loadbalancer-standalone-apoc
  namespace: default
spec:
  # References the standalone deployment above
  clusterRef: loadbalancer-standalone

  # APOC plugin configuration
  name: apoc
  version: "5.26.0"
  enabled: true

  # Plugin source - official Neo4j repository
  source:
    type: official

  # APOC configuration via environment variables (Neo4j 5.26+ approach)
  config:
    "apoc.export.file.enabled": "true"
    "apoc.import.file.enabled": "true"
    "apoc.import.file.use_neo4j_config": "true"

---
# Access Instructions:
#
# 1. Wait for LoadBalancer to provision:
#    kubectl get svc loadbalancer-standalone-service -w
#
# 2. Get the external IP/hostname:
#    kubectl get svc loadbalancer-standalone-service -o jsonpath='{.status.loadBalancer.ingress[0].*}'
#
# 3. Connect to Neo4j:
#    - Browser: http://<external-ip>:7474
#    - Bolt: bolt://<external-ip>:7687
#
# 4. Check service details:
#    kubectl describe svc loadbalancer-standalone-service
