# NodePort Service Example for Neo4j Enterprise Standalone
# This example shows how to expose a standalone Neo4j instance using NodePort
# Suitable for on-premises or development environments

apiVersion: v1
kind: Secret
metadata:
  name: neo4j-admin-secret
type: Opaque
stringData:
  username: neo4j
  password: changeme123!  # CHANGE THIS IN PRODUCTION

---
apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseStandalone
metadata:
  name: nodeport-standalone
spec:

  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent

  storage:
    className: standard
    size: "10Gi"

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

  # NodePort service configuration
  service:
    type: NodePort

    # Optional: Annotations
    annotations:
      example.com/team: "data-engineering"

  # Authentication
  auth:
    provider: native
    adminSecret: neo4j-admin-secret

  # Environment variables

  # Configuration
  config:
    # Memory settings (smaller for dev/test)
    server.memory.heap.initial_size: "512m"
    server.memory.heap.max_size: "1G"
    server.memory.pagecache.size: "512m"

    # Development settings
    dbms.logs.query.enabled: "INFO"
    dbms.logs.query.threshold: "100ms"

    # Enable browser on all interfaces
    server.default_listen_address: "0.0.0.0"

---
# Access Instructions:
#
# 1. Get the NodePort assignments:
#    kubectl get svc nodeport-standalone-service
#
#    Example output:
#    NAME                          TYPE       CLUSTER-IP     PORT(S)
#    nodeport-standalone-service   NodePort   10.96.1.2      7474:31474/TCP,7687:31687/TCP
#
# 2. Get a node IP address:
#    kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}'
#
#    Or for internal IP:
#    kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'
#
# 3. Connect to Neo4j:
#    - Browser: http://<node-ip>:31474  (use your actual NodePort)
#    - Bolt: bolt://<node-ip>:31687     (use your actual NodePort)
#
# 4. Alternative: Use port-forward for easier local access:
#    kubectl port-forward svc/nodeport-standalone-service 7474:7474 7687:7687
#
#    Then connect to:
#    - Browser: http://localhost:7474
#    - Bolt: bolt://localhost:7687
