apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: neo4j-2025-cluster
  namespace: default
spec:
  image:
    repo: neo4j
    tag: "2025.02.0-enterprise"
    pullPolicy: IfNotPresent
  topology:
    servers: 2        # Two servers for testing
  storage:
    className: standard
    size: "10Gi"
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2"
  tls:
    mode: disabled
