apiVersion: neo4j.neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: neo4j-526-cluster
  namespace: default
spec:
  edition: enterprise
  image:
    repo: neo4j
    tag: "5.26-enterprise"
    pullPolicy: IfNotPresent
  topology:
    primaries: 2      # Two primaries for testing
    secondaries: 0    # No secondaries for simplicity
  storage:
    className: standard
    size: "10Gi"
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2"
  tls:
    mode: disabled
  env:
    - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      value: "yes"
