#!/usr/bin/env bash
#
# sync-editor-viewer-roles.sh
#
# Generates per-CRD editor and viewer ClusterRoles (kubebuilder-style
# scaffolding) for every CRD in config/crd/bases/, plus regenerates the
# config/rbac/kustomization.yaml entries that include them.
#
# These roles aren't used by the operator itself; they exist as
# convenience cluster-roles end-users can bind to teams (e.g. via
# RoleBindings) to grant edit/view access to specific Neo4j CRs without
# granting cluster-admin.
#
# Inputs: spec.group, spec.names.plural, spec.names.singular from each CRD.
# Outputs:
#   config/rbac/<singular>_editor_role.yaml
#   config/rbac/<singular>_viewer_role.yaml
# and an updated config/rbac/kustomization.yaml resources block.

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
YQ="${YQ:-${ROOT}/bin/yq}"
CRD_DIR="${ROOT}/config/crd/bases"
RBAC_DIR="${ROOT}/config/rbac"
KUSTOMIZATION="${RBAC_DIR}/kustomization.yaml"

if [[ ! -x "$YQ" ]]; then
    echo "error: yq not found at $YQ. Run 'make yq' first." >&2
    exit 1
fi

write_role() {
    local file=$1 name=$2 group=$3 plural=$4 verbs=$5 status_verbs=$6 comment=$7
    cat > "$file" <<EOF
# permissions for end users to ${comment} ${plural}.
# This file is GENERATED by 'make sync-editor-viewer-roles'. DO NOT EDIT.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: neo4j-operator
    app.kubernetes.io/managed-by: kustomize
  name: ${name}
rules:
- apiGroups:
  - ${group}
  resources:
  - ${plural}
  verbs:
${verbs}
- apiGroups:
  - ${group}
  resources:
  - ${plural}/status
  verbs:
${status_verbs}
EOF
}

EDITOR_VERBS="  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch"
EDITOR_STATUS_VERBS="  - get"
VIEWER_VERBS="  - get
  - list
  - watch"
VIEWER_STATUS_VERBS="  - get"

# Generate editor + viewer for every CRD.
generated_files=""
for f in $(ls "$CRD_DIR"/*.yaml | sort); do
    group=$("$YQ" '.spec.group' "$f")
    plural=$("$YQ" '.spec.names.plural' "$f")
    singular=$("$YQ" '.spec.names.singular' "$f")
    [[ "$singular" == "null" || -z "$singular" ]] && {
        echo "warn: $f has no spec.names.singular; skipping" >&2
        continue
    }

    editor="${RBAC_DIR}/${singular}_editor_role.yaml"
    viewer="${RBAC_DIR}/${singular}_viewer_role.yaml"

    write_role "$editor" "${singular}-editor-role" "$group" "$plural" "$EDITOR_VERBS" "$EDITOR_STATUS_VERBS" "edit"
    write_role "$viewer" "${singular}-viewer-role" "$group" "$plural" "$VIEWER_VERBS" "$VIEWER_STATUS_VERBS" "view"

    generated_files+=" ${singular}_editor_role.yaml ${singular}_viewer_role.yaml"
done

# Build a sorted, comma-separated YAML array of every kustomize-managed
# RBAC source (the static base + the generated editor/viewer roles).
core_files=(
    "service_account.yaml"
    "role.yaml"
    "role_binding.yaml"
    "leader_election_role.yaml"
    "leader_election_role_binding.yaml"
    "metrics_auth_role.yaml"
    "metrics_auth_role_binding.yaml"
    "metrics_reader_role.yaml"
)

all_files=""
for f in "${core_files[@]}"; do
    all_files+="\"${f}\","
done
for f in $(echo "$generated_files" | tr ' ' '\n' | sort -u); do
    [[ -z "$f" ]] && continue
    all_files+="\"${f}\","
done
all_files="[${all_files%,}]"

"$YQ" -i ".resources = ${all_files}" "$KUSTOMIZATION"
echo "Wrote $(echo "$generated_files" | wc -w | tr -d ' ') editor/viewer role files"
echo "Updated $KUSTOMIZATION"
