package serverconfig

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"sort"
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"github.com/neo-technology-field/ps-kubernetes-operator/src/internal/render"
)

// ConfigChecksumAnnotation triggers a rolling restart when server config changes (AC-NEO-CONFIG-CHANGE).
const ConfigChecksumAnnotation = "neo4j.com/config-checksum"

// ConfigChecksumEnv is set on the Neo4j container so pod template changes force a rollout.
const ConfigChecksumEnv = "NEO4J_OPERATOR_CONFIG_CHECKSUM"

// ConfigMap builds the neo4j.conf ConfigMap for Standalone (BDR-008).
func ConfigMap(ctx render.Context) *corev1.ConfigMap {
	data := map[string]string{
		"neo4j.conf": renderNeo4jConf(ctx),
	}
	if jvm := renderJVMConf(ctx); jvm != "" {
		data["jvm.options"] = jvm
	}
	if apoc := renderApocConf(ctx); apoc != "" {
		data["apoc.conf"] = apoc
	}

	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      ctx.ConfigMapName(),
			Namespace: ctx.Namespace(),
			Labels:    ctx.CommonLabels("config"),
		},
		Data: data,
	}
}

// ConfigChecksum returns a stable SHA-256 digest of rendered ConfigMap data.
func ConfigChecksum(ctx render.Context) string {
	data := ConfigMap(ctx).Data
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	h := sha256.New()
	for _, k := range keys {
		h.Write([]byte(k))
		h.Write([]byte{0})
		h.Write([]byte(data[k]))
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))
}

func renderNeo4jConf(ctx render.Context) string {
	lines := []string{
		"# Generated by neo4j-operator",
	}
	if ctx.Neo4j.Spec.Config != nil && ctx.Neo4j.Spec.Config.Neo4j != nil {
		keys := make([]string, 0, len(ctx.Neo4j.Spec.Config.Neo4j))
		for k := range ctx.Neo4j.Spec.Config.Neo4j {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			lines = append(lines, k+"="+ctx.Neo4j.Spec.Config.Neo4j[k])
		}
	}
	return strings.Join(lines, "\n") + "\n"
}

func renderJVMConf(ctx render.Context) string {
	if ctx.Neo4j.Spec.Config == nil || ctx.Neo4j.Spec.Config.JVM == nil {
		return ""
	}
	jvm := ctx.Neo4j.Spec.Config.JVM
	if len(jvm.AdditionalArguments) == 0 {
		return ""
	}
	var buf bytes.Buffer
	for _, arg := range jvm.AdditionalArguments {
		buf.WriteString(arg)
		buf.WriteByte('\n')
	}
	return buf.String()
}

func renderApocConf(ctx render.Context) string {
	if ctx.Neo4j.Spec.Config == nil || ctx.Neo4j.Spec.Config.Apoc == nil || len(ctx.Neo4j.Spec.Config.Apoc) == 0 {
		return ""
	}
	keys := make([]string, 0, len(ctx.Neo4j.Spec.Config.Apoc))
	for k := range ctx.Neo4j.Spec.Config.Apoc {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	lines := []string{"# Generated by neo4j-operator"}
	for _, k := range keys {
		lines = append(lines, k+"="+ctx.Neo4j.Spec.Config.Apoc[k])
	}
	return strings.Join(lines, "\n") + "\n"
}
