package serverconfig

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	neo4jv1beta1 "github.com/neo4j/neo4j-kubernetes-operator/src/api/v1beta1"
	"github.com/neo4j/neo4j-kubernetes-operator/src/internal/render"
	"github.com/neo4j/neo4j-kubernetes-operator/src/internal/render/plugins"
)

// ConfigChecksumAnnotation triggers a rolling restart when server config changes (AC-NEO-CONFIG-CHANGE).
const ConfigChecksumAnnotation = "neo4j.com/config-checksum"

// ConfigChecksumEnv is set on the Neo4j container so pod template changes force a rollout.
const ConfigChecksumEnv = "NEO4J_OPERATOR_CONFIG_CHECKSUM"

// ConfigMap builds the neo4j.conf fragment ConfigMap for a pool (Helm parity: one key per setting).
func ConfigMap(ctx render.Context) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      ctx.ConfigMapName(),
			Namespace: ctx.Namespace(),
			Labels:    ctx.CommonLabels("config"),
		},
		Data: neo4jConfData(ctx),
	}
}

// ApocConfigMap builds apoc.conf when APOC is assigned and spec.config.apoc is set.
func ApocConfigMap(ctx render.Context) *corev1.ConfigMap {
	if !HasApocConfig(ctx) {
		return nil
	}
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      ctx.ApocConfigMapName(),
			Namespace: ctx.Namespace(),
			Labels:    ctx.CommonLabels("config"),
		},
		Data: map[string]string{
			"apoc.conf": renderApocConf(ctx),
		},
	}
}

// HasApocConfig reports whether apoc.conf should be mounted for this pool.
func HasApocConfig(ctx render.Context) bool {
	return plugins.Assigned(ctx.PoolPluginIDs(), "apoc") && renderApocConf(ctx) != ""
}

func neo4jConfData(ctx render.Context) map[string]string {
	data := mergedNeo4jConf(ctx)
	if jvm := renderJVMConf(ctx); jvm != "" {
		data["server.jvm.additional"] = strings.TrimSuffix(jvm, "\n")
	}
	return data
}

// ConfigChecksum returns a stable SHA-256 digest of rendered ConfigMap data.
func ConfigChecksum(ctx render.Context) string {
	data := neo4jConfData(ctx)
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	h := sha256.New()
	for _, k := range keys {
		h.Write([]byte(k))
		h.Write([]byte{0})
		h.Write([]byte(data[k]))
		h.Write([]byte{0})
	}
	if HasServerLogsXml(ctx) {
		h.Write([]byte(serverLogsFileName))
		h.Write([]byte{0})
		h.Write([]byte(ctx.Neo4j.Spec.Logging.ServerLogsXml))
		h.Write([]byte{0})
	} else if HasServerLogsConfigMapRef(ctx) {
		// External CM content is not hashed — changing the CM alone does not roll pods.
		h.Write([]byte("serverLogsConfigMapRef"))
		h.Write([]byte{0})
		h.Write([]byte(ServerLogsConfigMapName(ctx)))
		h.Write([]byte{0})
		h.Write([]byte(ServerLogsConfigMapKey(ctx)))
		h.Write([]byte{0})
	}
	if HasUserLogsXml(ctx) {
		h.Write([]byte(userLogsFileName))
		h.Write([]byte{0})
		h.Write([]byte(ctx.Neo4j.Spec.Logging.UserLogsXml))
		h.Write([]byte{0})
	} else if HasUserLogsConfigMapRef(ctx) {
		h.Write([]byte("userLogsConfigMapRef"))
		h.Write([]byte{0})
		h.Write([]byte(UserLogsConfigMapName(ctx)))
		h.Write([]byte{0})
		h.Write([]byte(UserLogsConfigMapKey(ctx)))
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))
}

func renderJVMConf(ctx render.Context) string {
	if ctx.Neo4j.Spec.Config == nil || ctx.Neo4j.Spec.Config.JVM == nil {
		return ""
	}
	jvm := ctx.Neo4j.Spec.Config.JVM
	if len(jvm.AdditionalArguments) == 0 {
		return ""
	}
	var buf bytes.Buffer
	for _, arg := range jvm.AdditionalArguments {
		buf.WriteString(arg)
		buf.WriteByte('\n')
	}
	return buf.String()
}

func renderApocConf(ctx render.Context) string {
	if ctx.Neo4j.Spec.Config == nil || ctx.Neo4j.Spec.Config.Apoc == nil || len(ctx.Neo4j.Spec.Config.Apoc) == 0 {
		return ""
	}
	keys := make([]string, 0, len(ctx.Neo4j.Spec.Config.Apoc))
	for k := range ctx.Neo4j.Spec.Config.Apoc {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	lines := []string{"# Generated by neo4j-operator"}
	for _, k := range keys {
		// APOC settings only — dbms.*/server.* belong in neo4j.conf (config.neo4j).
		// See https://neo4j.com/docs/apoc/current/config/
		if !strings.HasPrefix(k, "apoc.") {
			continue
		}
		lines = append(lines, k+"="+ctx.Neo4j.Spec.Config.Apoc[k])
	}
	if len(lines) == 1 {
		return ""
	}
	return strings.Join(lines, "\n") + "\n"
}

// ValidateConfigReports rejects neo4j.conf keys under config.apoc (CFG-APOC-001).
func ValidateConfig(neo4j *neo4jv1beta1.Neo4j) error {
	if neo4j.Spec.Config == nil || neo4j.Spec.Config.Apoc == nil {
		return nil
	}
	var bad []string
	for k := range neo4j.Spec.Config.Apoc {
		if !strings.HasPrefix(k, "apoc.") {
			bad = append(bad, k)
		}
	}
	if len(bad) == 0 {
		return nil
	}
	sort.Strings(bad)
	return fmt.Errorf("config.apoc only accepts apoc.* keys for apoc.conf; move %v to config.neo4j (neo4j.conf)", bad)
}
