# Development Property Sharding Example
# This example is optimized for development and testing environments
#
# DEVELOPMENT NOTES:
# - Still requires 5 servers minimum (property sharding constraint)
# - Uses minimum viable resource allocation (4GB memory, 2 CPU cores)
# - Suitable for learning, testing, and small-scale development
# - NOT recommended for production workloads
# - Consider using regular Neo4j clusters for basic development
#
# ALTERNATIVE: For pure development without property sharding features,
# use examples/clusters/development-cluster.yaml instead

# Prerequisites: Create admin secret (REQUIRED)
# kubectl create secret generic neo4j-admin-secret \
#   --from-literal=username=neo4j \
#   --from-literal=password=dev-password

# Development property sharding cluster with minimal resources
apiVersion: neo4j.com/v1alpha1
kind: Neo4jEnterpriseCluster
metadata:
  name: dev-sharding-cluster
  namespace: neo4j-dev
  labels:
    environment: development
    purpose: testing
spec:
  image:
    repo: neo4j
    tag: 2025.07.1-enterprise

  # Authentication required for property sharding
  auth:
    adminSecret: neo4j-admin-secret

  # Minimum required servers for property sharding
  topology:
    servers: 5  # Property sharding requires 5+ servers

  storage:
    size: 2Gi  # Small storage for dev
    className: standard

  # Development resources (minimum viable for property sharding)
  resources:
    requests:
      memory: 4Gi    # Absolute minimum for property sharding (8GB+ recommended for production)
      cpu: 2000m     # 2 cores for cross-shard queries
    limits:
      memory: 8Gi    # Recommended for property sharding workloads
      cpu: 2000m     # Stable performance

  # Enable property sharding with development-friendly settings
  propertySharding:
    enabled: true
    config:
      # Default required settings applied automatically

      # Development-specific tuning
      db.tx_log.rotation.retention_policy: "2 days"    # Shorter retention
      internal.dbms.sharded_property_database.property_pull_interval: "50ms"  # Less aggressive

      # Memory settings for development
      server.memory.heap.max_size: "4G"
      server.memory.pagecache.size: "1G"

      # Enable more logging for development
      dbms.logs.debug.level: "INFO"

---
# Simple sharded database for testing
apiVersion: neo4j.com/v1alpha1
kind: Neo4jShardedDatabase
metadata:
  name: test-sharded-db
  namespace: neo4j-dev
  labels:
    purpose: testing
    dataset: sample
spec:
  clusterRef: dev-sharding-cluster

  name: testdata

  defaultCypherLanguage: "25"

  propertySharding:
    # Small number of shards for testing
    propertyShards: 2

    hashFunction: murmur3

    # Test property distribution
    includedProperties:
      - "description"      # Test large text fields
      - "metadata"        # Test JSON data
      - "test_payload"    # Test data for experiments

    excludedProperties:
      - "id"              # Keep IDs in graph
      - "name"            # Frequently accessed
      - "type"            # Used in queries

    # Simple topology for development
    graphShard:
      primaries: 1    # Single primary for dev
      secondaries: 1  # One backup

    propertyShardTopology:
      primaries: 1    # Single primary per shard
      secondaries: 0  # No replicas in dev

  wait: true
  ifNotExists: true

---
# Development namespace
apiVersion: v1
kind: Namespace
metadata:
  name: neo4j-dev
  labels:
    purpose: development
    environment: dev

---
# Simple admin credentials for development
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-admin-secret
  namespace: neo4j-dev
type: Opaque
stringData:
  username: "neo4j"
  password: "development123"
